---
- name: Set Up Envrionment to run Kafka
  hosts: localhost
  tasks:
    - name: Check if Kafka has been downloaded
      become: true
      become_user: root
      ansible.builtin.stat:
        path: /opt/kafka/bin
      register: ansible_facts
    - name: Check if Zookeeper directory exists
      become: true
      become_user: root
      ansible.builtin.stat:
        path: /tmp/zookeeper
      register: zookeeper_check
    - name: Create Zookeeper Directory
      become: true
      become_user: root
      ansible.builtin.file:
        path: /tmp/zookeeper
        state: directory
        mode: '0755'
      when: ansible_facts.stat.exists and zookeeper_check.stat.exists == False
    - name: Set Up zookeeper IDs
      become: true
      become_user: root
      ansible.builtin.shell: "BROKER_ID=1;echo $BROKER_ID > /tmp/zookeeper/myid"
      when: ansible_facts.stat.exists and zookeeper_check.stat.exists == False
    - name: Create Startup bash script
      become: true
      become_user: root
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          /opt/kafka/bin/zookeeper-server-start.sh -daemon /opt/kafka/config/zookeeper.properties
          /opt/kafka/bin/kafka-server-start.sh -daemon /opt/kafka/config/server.properties
        dest: /opt/kafka/startup.sh
        mode: '0755'
      when: ansible_facts.stat.exists and zookeeper_check.stat.exists == False
    - name: Create Stop bash script
      become: true
      become_user: root
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          /opt/kafka/bin/kafka-server-stop.sh
          /opt/kafka/bin/zookeeper-server-stop.sh
        dest: /opt/kafka/stop.sh
        mode: '0755'
      when: ansible_facts.stat.exists and zookeeper_check.stat.exists == False